### ISSUE TITLE
popup banner

### ISSUE THREAD

**Issue by robshep** [NorthWalesTech/Community#28]
SuperTemps have provisionally agreed to buy us a popup banner.

Maybe Ronan could mock up a design please?

sponsors at the bottom probably - logos to follow 

MicroGraphics make them locally. 
I think about £150

**Comment by carwyn** [comment]
I'll get in touch with him.

**Comment by davehun** [comment]
I ahve an offer from our graphic designer Nanimo to do this ..

**Comment by carwyn** [comment]
The SVG for the NWTech logo is in the git repo, there are two I need to take out though as they don't work.

**Comment by Tsany** [comment]
Nanimo was taken, so I'm Tsany here, but yes, I can design a popup banner. 

What kind of dimensions are you thinking of, and what kind of info would you like to display?  Any photos you want to incorporate?

**Comment by carwyn** [comment]
We'd need to get the dimensions from one of the printing companies, it's worth asking them if they'd be willing to become sponsors too. Needs to be non date specific, possibly with a space for stick-on info panels?

**Comment by robshep** [comment]
Supertemps are sponsoring the banner, here's their Logo

[supertemps+.eps.zip](https://github.com/NorthWalesTech/NorthWalesTech/files/202319/supertemps.eps.zip)

In addtion, for printing etc, here are the logo color details.
Green Colour Pantone: 376  
RGB: R 127 G 186 B 0

**Comment by carwyn** [comment]
http://www.pop-upbanners.com/

There are some nice indoor/outdoor ones available.

**Comment by carwyn** [comment]
http://www.micrographics.co.uk/exhibition-main/bannerstands/

**Comment by carwyn** [comment]
Stale.
