### ISSUE TITLE
Food Scanner for Pay What you Feel Cafe

### ISSUE THREAD

**Issue by carwyn** [NorthWalesTech/Community#36]
One area I related they could  really do with some help with is in barcode scanning. After I drop off all the free food from the supermarket at 9pm some poor volunteer is currently going through each item noting down it's weight and the name of the produce and what supermarket it came from to audit  the food. This is totally laborious work and cries out for automation with a simple barcode scanner linked to an online grocery API (I'm this must exist). If we could produce a spreadsheet with all the items + weights this would be a big help. Reckon this should be possible, could run from a raspberry pi + small TFT we could donate. Or an Android app using phone camera as barcode reader.

**Comment by lukepfarrar** [comment]
http://www.ean-search.org/perl/ean-search.pl?q=5012427141605

**Comment by lukepfarrar** [comment]
http://www.amazon.co.uk/PROZOR-Automatic-Barcode-Scanner-Optical/dp/B00NIOEA1K/ref=sr_1_3?ie=UTF8&qid=1460126794&sr=8-3&keywords=barcode+scanner

**Comment by davehun** [comment]
Camera phones are better at scanning barcodes than a bar code scanner

**Comment by carwyn** [comment]
I'm liking this community project idea tied to a venue with regular informal meetups to work on it :)

**Comment by davehun** [comment]
sure I have a few other questions for @glynhudson does the food all have bar codes and stickers ? 
could we just take a pick of the sticker to ID.
Could even get a bluetooth balance they are ~ £50 to fully automate it

**Comment by glynhudson** [comment]
Yes all the food has barcodes. A BT scales is a good idea, paired with a barcode scanner this would be a totally automated solution. 

I like the idea of a hack session at the venue, let's wait until they get wifi sorted since there is no mobile signal or wifi currently.

I should mention in have not mentioned the idea to Denise yet, it's just an observation I made having to do the food recording manually and thought there must be a better way!

**Comment by carwyn** [comment]
I've started a conversation with Denise about screening her and Jo's TEDx talks there when her's is up. From there I think a regular hack session there is a good idea. There's a lot of scope for collaborating with PAYF as it has a similar community feel to it :) Going to pop down on Friday to see them.

**Comment by carwyn** [comment]
PAYF Cafe now closed :(
