### ISSUE TITLE
DIY BYOD IOT event

### ISSUE THREAD

**Issue by davehun** [NorthWalesTech/Community#71]
# DIY IOT event.
Need to find a venue where we can dissasemble and reassembe
[these](https://www.itead.cc/smart-socket.html)
will need ~ month + notice to allow people to buy them.
need a usb to rs232 adatper @glynhudson can maybe lend us some.
No soldering iron needed but location will need wifi and extension leads.
The devices are CE marked.

**Comment by robshep** [comment]
Excellent idea.  I'd be very keen for this. 

Presumably re-flashing them with some replacement firmware?

**Comment by davehun** [comment]
yes mqtt enabled

**Comment by robshep** [comment]
👍

**Comment by carwyn** [comment]
Arguably superseded by the Year of IoT
