### ISSUE TITLE
Event: Wireless & Radio

### ISSUE THREAD

**Issue by robshep** [NorthWalesTech/Community#72]
> **Simon Taylor, Dragin ARC on Facebook**  
> a gentleman from Caernarfon who worked for the Post Office was instrumental in supporting the young Marconi. I would happily come and talk to North Wales Tech about the beginnings of the wireless age and its strong North Wales connection

Plus...

* LoraWan  (RS)
* Packet Radio (Dragon)
* SATNOGS (JH)
* ADSB (Flight Aware 1090 etc) (DH, RS or maybe Gary Smith?)

**Comment by davehun** [comment]
ohh nice.
I have adsb running for a while it was rather fun combined with a kml viewer

**Comment by robshep** [comment]
Yeah, I've been tracked SAR Aircraft from a station in Nant Peris :)  

https://gist.github.com/robshep/43a58b7bb0505e8227c5e9f95acdc541#file-points-geojson

**Comment by davehun** [comment]
I got a few during their trainning

https://gist.github.com/davehun/b60630df1836ce13eed84232b519aa52 <https://gist.github.com/davehun/b60630df1836ce13eed84232b519aa52>

**Comment by carwyn** [comment]
Simon's checking a few things with regards to public liability at the site but as long as we get past that he's up for putting it up on the NWT Meetup with ARC as co-organisers to reach the further catchment.

**Comment by carwyn** [comment]
This would be for April 21st on the old Marconi site.

**Comment by robshep** [comment]
I didn't glue those together sorry - was just dumping ideas for another tech talks evening. 

I can't make it on the 21st April so will plead to find another date for Simon's talk :) 

Otherwise, just co-opt this issue to the April 21st Event and I'll have a nice family holiday trying to forget this interesting stuff is going on back home :)

**Comment by carwyn** [comment]
Both! :) 21st is ARC's own thing, we'd just be publicity really. I'm sure they'd be up for coming along to join in an NWT radio event. Been talking to Simon for a while about possible collaboration on a Makefest one day!

**Comment by carwyn** [comment]
We did a few of these.
