### ISSUE TITLE
Event: Emerging Languages

### ISSUE THREAD

**Issue by robshep** [NorthWalesTech/Community#76]
**Wednesday 19th December**

**Most Likely Pointio?**

**Languages:** 
- [ ] Zig https://ziglang.org/
- [ ] Nim https://nim-lang.org/
- [ ] ? one more

**Format (like the JVM languages event)**
* 3 or 4 groups of any size pick a different language each
* A Basic but multi-faceted programming task, so different people can work on different elements
** Download a web resource
** parse some json
** something with data structures
** some output
* A show & tell at the end with a quick description of the code, what was hard, what was easy etc.

**Event timings**
* Intro (20m)
* 1hr programming
* pizza!
* 1hr of 15min quickfire show & tell

**Comment by jonbullock** [comment]
How about Rust as the other language?

**Comment by carwyn** [comment]
We did this :)
